# A name to give to this evaluation configuration
name: emphasis-annotation

# The type of test to run. One of [ab, abx, mos, mushra, wordselect].
test: wordselect

# The type of data to use. One of [audio, image, text, video].
datatype: audio

# The location to store files used for evaluation. One of [aws].
storage: aws

# The third-party platform hosting the MySQL database. One of [heroku].
database: heroku

# The third-party platform hosting the server. One of [heroku].
server: heroku

# Crowdsourcing configuration
crowdsource:

  # The crowdsourcing platform used for evaluation. One of [mturk].
  platform: mturk

  # The survey title shown to potential participants
  title: Emphasis annotation

  # The survey description shown to potential participants
  description: "Participate in a research study by listening to English speech and selecting emphasized words. Requires headphones and a quiet listening environment to pass listening test prescreening. $2.89 bonus on completion. Estimated 15 minutes ($13.35 / hour)."

  # Keywords that participants can use to find your survey
  keywords: annotate, audio, emphasis, headphones, speech

  # Filter participants
  filter:

    # Only allow participants from a certain countries
    countries: ['US']

    # Only allow participants who have previously completed at least this
    # number of tasks
    approved_tasks: 250

    # Only allow participants who have a sufficiently high acceptance rating
    approval_rating: 98

  # How much you pay participants (in US dollars)
  # E.g., 2.00 is two dollars; 0.50 is fifty cents
  payment:

    # The amount that you pay even if they don't pass prescreening
    base: 0.45

    # The additional amount that you pay participants who complete evaluation
    completion: 2.89

  # How long to wait for things (in seconds)
  duration:

    # Total lifespan of the evaluation, after which the evaluation is no
    # longer available for participants to take
    total: 604800

    # The maximum time you will allow a participant to spend on your task
    assignment: 5400

    # Duration after which payment is automatically made
    autoapprove: 172800

# The number of participants
participants: 2212

# The number of evaluations each participant performs
samples_per_participant: 30

# A seed to use for deterministic random sampling
random_seed: 0

# Introduction text to display on the first page participants visit
welcome_text: "
  # **Consent to Participate in Research**\n
  **Title of Research Study:** Datasets and Scaling Laws for Neural Emphasis Prediction\n\n
  **Principal Investigator:** Dr. Bryan Pardo, Department of Computer Science, Northwestern University\n\n
  **Supported By:** This research is supported by Sony Research.\n\n
  **Key Information about this research study:**\n\n
  The following is a short summary of this study to help you decide whether to be a part of this study. Information that is more detailed is explained later on in this form.\n\n
  The purpose of this study is to learn how English speakers perceive emphasis. You will be asked to listen to recorded samples of English speech and rate words and phrases in the speech for qualities you perceive as related to the prominence of words or phrases.
  We expect that you will be in this research study for about 15 minutes. There are no risks associated with participation in the proposed research beyond what you experience from using a computer in everyday life, or boredom. The main benefit is the satisfaction of contributing to linguists' knowledge concerning the speech perception system.\n\n
  **Why am I being asked to take part in this research study?**\n\n
  We are asking you to take part in this research study because you are a speaker of American English at least 18 years of age, with no known deficits in speech, hearing or reading, and with normal or corrected-to-normal vision.\n\n
  **How many people will be in this study?**\n\n
  We expect about 2212 people will be in this research study.\n\n
  **What should I know about participating in a research study?**\n\n
  - Whether or not you take part is up to you.\n
  - You can choose not to take part.\n
  - You can agree to take part and later change your mind.\n
  - Your decision will not be held against you.\n\n
  **What happens if I say, \"Yes, I want to be in this research\"?**\n\n
  If you agree to participate, you will first be required to pass a listening test. If you do not pass, the survey will end and you will be compensated $0.45. If you pass the listening test, you will be asked to identify emphases that you hear in the words and phrases of recorded samples of English. You will enter your responses by clicking on the words corresponding to the speech you hear, as presented on the computer screen. You will advance through the experiment at your own pace. Once you are finished, you will be asked two follow-up questions about your language background. Participants who finish these follow-up questions receive a bonus of $2.89 for a total of $3.34. The experiment will take place in one session and will last an average of 15 minutes and no longer than 30 minutes. You will participate in the experiment remotely, using your computer and your headphones, in a quiet location of your choosing. You will not directly interact with any member of the study team.\n\n
  **What happens if I do not want to be in this research?**\n\n
  Participation in research is voluntary. You can decide to participate or not to participate.\n\n
  **What happens if I say \"Yes\", but I change my mind later?**\n\n
  You can leave the research at any time and it will not be held against you. If you withdraw before completing the experiment, all data collected from you will be discarded without analysis.\n\n
  **Will being in this study help me in any way?**\n\n
  We cannot promise any benefits to you or others from your taking part in this research. However, this study may benefit society if the results lead to a better understanding of how people perceive speech.\n\n
  **Is there any way being in this study could be bad for me?**\n\n
  A possible risk for any research is that confidentiality could be compromised—that is, that people outside the study might get hold of confidential study information. We will do everything we can to minimize this risk, as described in more detail later in this form. As well, please make sure your volume is at an appropriate level and not too loud in order to prevent hearing loss.\n\n
  **How will the researchers protect my information?**\n\n
  We will remove or code any personal information that could identify you before files are shared with other researchers to ensure that, by current scientific standards and known methods, no one will be able to identify you from the information we share. This includes deidentifying your MTurk Worker ID from your results: MTurk Worker IDs will not be released. Despite these measures, we cannot guarantee anonymity of your personal data.\n\n
  **Who will have access to the information collected during this research study?**\n\n
  Efforts will be made to limit the use and disclosure of your personal information, including research study records, to people who have a need to review this information. We cannot promise complete secrecy.\n\n
  There are reasons why information about you may be used or seen by other people beyond the research team during or after this study. Examples include:\n\n
  - University officials, government officials, study funders, auditors, and the Institutional Review Board may need access to the study information to make sure the study is done in a safe and appropriate manner.\n
  - The research team may give information to appropriate authorities for reasons of health and safety—for example, if you indicate that you plan to harm yourself or others, or for public health reasons.\n\n
  **How might the information collected in this study be shared in the future?**\n\n
  We will keep the information we collect about you during this research study for study recordkeeping and for potential use in future research projects. De-identified data from this study may be shared with the research community, with journals in which study results are published, and with databases and data repositories used for research. We will remove or code any personal information that could directly identify you before the study data are shared. Despite these measures, we cannot guarantee anonymity of your personal data.\n\n
  Unless you revoke your consent, it will not expire. You may revoke consent to participation in this research at any time and in any format. To revoke your authorization, write to:\n\n
  PI's Name: Bryan Pardo, Ph.D.\n\n
  Institution: Northwestern University\n\n
  Department: Computer Science\n\n
  Address: 2233 Tech Drive, Evanston, IL 60208\n\n
  **Will I be paid or given anything for taking part in this study?**\n\n
  For your participation in this study, you will receive compensation through the online platform. Participants who complete the study are paid $3.34 ($0.45 + $2.89 bonus), while participants who fail the listening test are paid $0.45. You will be compensated within 48 hours of completing the study. If you voluntarily withdraw from the study before completion, you will be paid for the portion that you completed.\n\n
  **Who can I talk to?**\n\n
  If you have questions, concerns, or complaints, or think the research has affected you in some way, talk to the Principal Investigator, at 847-491-7184 or pardo@northwestern.edu, or the Student Investigator, at morrimax@u.northwestern.edu.\n\n
  This research has been reviewed and approved by an Institutional Review Board (\"IRB\")—an IRB is a committee that protects the rights of people who participate in research studies. You may contact the IRB by phone at (312) 503-9338 or by email at irb@northwestern.edu if:\n\n
  - Your questions, concerns, or complaints are not being answered by the research team.\n
  - You cannot reach the research team.\n
  - You want to talk to someone besides the research team.\n
  - You have questions about your rights as a research participant.\n
  - You want to get information or provide input about this research.\n\n
  **Consent**\n\n
  If you want a copy of this consent for your records, you can print it from this screen.\n\n
  If you wish to participate, please click the \"I Agree\" button and you will be taken to the survey.\n\n
  If you do not wish to participate in this study, please close this tab or window (e.g., by selecting X in the corner of your browser).
  "

# Questions that participants must answer before they are permitted to
# perform evaluation. If a multiple choice question has correct_answer
# defined, the participant must select that answer to be able to continue
# to the evaluation.
prescreen_questions: []

# Include an audio listening test
listening_test:

  # Listening test instructions
  instructions: "
    ## **Instructions** \nMake sure your headphones are on and your volume
    is turned up to a comfortable level. Listen to the audio. Then, select
    how many tones you heard."

  # Number of questions to include on the listening test
  num_questions: 2

  # Number of allowed retries before the participant fails the test
  retries: 2

# Instructions presented to the participant during evaluation
survey_instructions: "

  ## **Instructions** \nListen to the audio file a minimum of two times.
  Select all of the words that were emphasized by the speaker. The emphasized
  words are those that stand out from nearby words. Play the audio and then
  click on a word to select (boldface) or deselect it."

# Questions presented to the participant after evaluation
followup_questions:

  # Ask participant for their native language
  - name: Language

    # The type of question. One of [free-response, multiple-choice].
    type: multiple-choice

    # Question text
    text: What is your native language?

    # Possible answers
    answers: [
      'Albanian',
      'Amharic',
      'Arabic',
      'Bengali',
      'Berber',
      'Creole',
      'Dari',
      'Dzongkha',
      'English',
      'Farsi',
      'Filipino',
      'French',
      'German',
      'Gujarati',
      'Hakka',
      'Hausa',
      'Hebrew',
      'Hindi',
      'Hokkien',
      'Indonesian',
      'Italian',
      'Japanese',
      'Javanese',
      'Kannada',
      'Korean',
      'Mandarin Chinese',
      'Marathi',
      'Nepali',
      'Nigerian Pidgin',
      'Oromo',
      'Pashto',
      'Patois',
      'Polish',
      'Portuguese',
      'Russian',
      'Spanish',
      'Swahili',
      'Somali',
      'Tagalog',
      'Tamil',
      'Telugu',
      'Thai',
      'Turkish',
      'Ukrainian',
      'Urdu',
      'Uzbek',
      'Vietnamese',
      'Western Punjabi',
      'Wu Chinese',
      'Yue Chinese',
      'Other']

  # Ask participant for their country of origin
  - name: Country

    # The type of question. One of [free-response, multiple-choice].
    type: multiple-choice

    # Question text
    text: What country/region did you live in during your childhood?

    # Possible answers
    answers: [
      'Afghanistan',
      'Albania',
      'Argentina',
      'Bangladesh',
      'Bhutan',
      'Brazil',
      'Cameroon',
      'Canada',
      'China',
      'Colombia',
      'Cuba',
      'Dominican Republic',
      'Ecuador',
      'Egypt',
      'El Salvador',
      'Ethiopia',
      'France',
      'Germany',
      'Ghana',
      'Guatemala',
      'Guyana',
      'Haiti',
      'Honduras',
      'India',
      'Iran',
      'Iraq',
      'Israel',
      'Jamaica',
      'Japan',
      'Jordan',
      'Kenya',
      'Mexico',
      'Morocco',
      'Nepal',
      'Nicaragua',
      'Nigeria',
      'Pakistan',
      'Peru',
      'Philippines',
      'Poland',
      'Russia',
      'Somalia',
      'South Korea',
      'Syria',
      'Taiwan',
      'Thailand',
      'Turkey',
      'Ukraine',
      'United Kingdom',
      'United States',
      'Uzbekistan',
      'Venezuela',
      'Vietnam',
      'Yemen',
      'Other']
